# Generated by Django 5.1.1 on 2024-11-21 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('username', models.CharField(default=' ', max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(default='null', max_length=50)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('qno', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('qname', models.CharField(default='null', max_length=50)),
                ('answer', models.CharField(default='null', max_length=50)),
                ('op1', models.CharField(default='null', max_length=50)),
                ('op2', models.CharField(default='null', max_length=50)),
                ('op3', models.CharField(default='null', max_length=50)),
                ('op4', models.CharField(default='null', max_length=50)),
                ('subject', models.CharField(default='null', max_length=50)),
            ],
            options={
                'db_table': 'Question',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('username', models.CharField(default=' ', max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(default='null', max_length=50)),
                ('score', models.IntegerField()),
            ],
            options={
                'db_table': 'result',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('username', models.CharField(default=' ', max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(default='null', max_length=50)),
                ('mobileno', models.IntegerField(default=0)),
                ('emailid', models.EmailField(default=' ', max_length=25)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
