# Generated by Django 5.1.1 on 2024-12-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='mobileno',
            field=models.IntegerField(default='null'),
        ),
    ]
